// STATUS
const DEFAULT_STATUS = "NOT DONE";
const IN_PROGRESS_STATUS = "IN PROGRESS";
const UNDER_REVIEW_STATUS = "UNDER REVIEW";
const BLOCKED_STATUS = "BLOCKED";
const DONE_STATUS = "DONE";

// PRIORITY
const HIGH_PRIORITY = "HIGH PRIORITY";
const MEDIUM_PRIORITY = "MEDIUM PRIORITY";
const LOW_PRIORITY = "LOW PRIORITY";

module.exports = {
  DEFAULT_STATUS,
  IN_PROGRESS_STATUS,
  UNDER_REVIEW_STATUS,
  BLOCKED_STATUS,
  DONE_STATUS,
  HIGH_PRIORITY,
  MEDIUM_PRIORITY,
  LOW_PRIORITY,
};
